name: PDF Action
run-name: Markdown to PDF
on:
  push:
    branches:
      - master
    paths:
      - src/**
      - styles/**
      - template/**
      - Dockerfile
      - docker-compose.yaml
      - package-lock.json
      - package.json
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-docker-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get TAG
        id: get-tag
        run: |
          T=$(echo "$GITHUB_REF" | sed -n 's|refs/tags/||p')
          echo "tag=${T:-latest}" >> $GITHUB_OUTPUT

      - name: Build the docker image
        run: |
          TAG="${{ steps.get-tag.outputs.tag }}" docker-compose build

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          TAG="${{ steps.get-tag.outputs.tag }}" docker-compose push
